# -*- coding: utf-8 -*-
"""Vinod_Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16WvW83WRX8G3JqqDH9IIQ_fvzYXXXbwg
"""

!nvidia-smi

!unzip -q "/content/Helmet Detection.v1i.yolov11.zip" -d "/content/Helmet Detection.v1i.yolov11"

!unzip -q "/content/dataset_5.zip"

root_dir = '/content/dataset_5'

!pip install ultralytics

!yolo train model = yolov8n.pt data=/content/Helmet_Detection/Helmet_Detection/data.yaml epochs=30 imgsz=640

!pip install supervision

import supervision as sv
from ultralytics import YOLO

# Load YOLOv8 model
model = YOLO("/content/runs/detect/train/weights/best.pt")

#Perform inference on an image
results = model("/content/img.jpg")

#convert detections to supervision format
detections = sv.Detections.from_ultralytics(results[0])

#Define multiple classes to count
selected_classes = ['With Helmet', 'Without Helmet']

#Get the correct class IDs from the dictionary
selected_class_ids = [class_id for class_id, name in model.names.items() if name in selected_classes]

#Ensure class IDs are found
print(f"Selected Class IDs: {selected_class_ids}")

#Apply filtering
import numpy as np
detections = detections[np.isin(detections.class_id, selected_class_ids)]

#Print the number of detections
print(f"Total objects detected for {selected_classes} : {len(detections)}")

print(model.names) #Display all class names

import cv2
import numpy as np
import supervision as sv
from ultralytics import YOLO
from google.colab.patches import cv2_imshow

# Load YOLOv8 model
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Run detection on an image
image_path = "/content/img.jpg"
image = cv2.imread(image_path)

if image is None:
    print(f"Error: Could not load image from {image_path}")
else:
    # Run YOLO model with a confidence threshold
    results = model.predict(image, conf=0.3)

    # Convert YOLO detections to Supervision's Detections object
    detections = sv.Detections.from_ultralytics(results[0])

    # Get class names from the YOLO model
    class_names = model.names
    print(f"Model class names: {class_names}")

    # Ensure class names match exactly with model.names
    selected_classes = ['With Helmet', 'Without Helmet']  # Corrected names

    # Get class IDs for the selected classes
    selected_class_ids = [class_id for class_id, name in class_names.items() if name in selected_classes]
    print(f"Selected class IDs: {selected_class_ids}")

    if not selected_class_ids:
        print("Warning: No matching class IDs found. Please check selected class names.")

    # Filter detections by selected class IDs
    mask = np.isin(detections.class_id, selected_class_ids)
    filtered_detections = detections[mask]

    # Count the detections per class
    class_counts = {class_names[class_id]: np.sum(filtered_detections.class_id == class_id) for class_id in selected_class_ids}
    print(f"Class counts: {class_counts}")

    # Annotate image with bounding boxes
    box_annotator = sv.BoxAnnotator()
    annotated_image = box_annotator.annotate(scene=image, detections=filtered_detections)

    # Display class counts on the image
    y_offset = 50
    for class_name, count in class_counts.items():
        text = f"{class_name}: {count}"
        cv2.putText(annotated_image, text, (50, y_offset), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
        y_offset += 40

    # Show the final annotated image
    cv2_imshow(annotated_image)

!pip install streamlit

!wget -q -O - ipv4.icanhazip.com

!streamlit run app.py & npx localtunnel --port 8501

!pip install streamlit

!wget -q -O - ipv4.icanhazip.com

!streamlit run app.py & npx localtunnel --port 8501